 <div id="order_remark_block" class="edit-order-comments">
  <div class="admin__page-section-title">
        <span class="title">Order Remark</span>
    </div>
	<div class="order-remark-block" id="remark_form">
    <ul class="note-list">
	<?php foreach ($block->getRemarkCollection() as $_item): ?>
           <li class="note-list-item">
		<span class="note-list-date"><?php echo $_item->getCreatedAt(); ?></span>
	        <span class="note-list-user">
	   	<?php echo $_item->getUser();?>
		</span>
	        <p><span class="note-list-customer">
	  	 <?php echo $_item->getRemark();?>
		</span></p>
	   </li>
	<?php endforeach; ?>
    </ul>
	<div class="admin__field">
                <label for="remark_comment" class="admin__field-label">
                    <?php /* @escapeNotVerified */ //echo __('Remark:') ?>
                </label>
                <div class="admin__field-control">
                    <textarea name="remark[comment]"
                              rows="3"
                              cols="5"
                              id="remark_comment"
                              class="admin__control-textarea" style="width: 100%; height: 140px;"></textarea>
                </div>
	</div>

	<div class="order-history-comments-actions">
                    <?php echo $block->getChildHtml('submit_button') ?>
	</div>

 </div>
</div>
